# =============================================================================
# network-config.yml - Configuration réseau statique de la VM
# =============================================================================

version: 2
ethernets:
  # L'interface réseau principale de la VM
  ens3:
    dhcp4: false              # Pas de DHCP, on configure en statique
    addresses:
      - ${ip}/24              # L'IP fixe avec le masque (ex: 192.168.122.10/24)
    gateway4: ${gateway}      # La gateway = l'hôte KVM (192.168.122.1)
    nameservers:
      addresses:
        - ${dns}              # Le DNS = libvirt fait aussi serveur DNS
        - 8.8.8.8             # Fallback sur Google DNS