[all:vars]
ansible_user=zeatop
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[base]
ci-cd          ansible_host=10.0.0.10
k8s-master     ansible_host=10.0.0.20
k8s-worker-1   ansible_host=10.0.0.21
k8s-worker-2   ansible_host=10.0.0.22
bdd            ansible_host=10.0.0.30
elk            ansible_host=10.0.0.40

[docker]
ci-cd

[containerd]
k8s-master
k8s-worker-1
k8s-worker-2

[kubernetes]
k8s-master
k8s-worker-1
k8s-worker-2

[k8s_master]
k8s-master

[k8s_workers]
k8s-worker-1
k8s-worker-2

[cicd]
ci-cd

[database]
bdd

[monitoring]
elk