- name: Vérifier si le cluster est déjà initialisé
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Initialisation du cluster Kubernetes
  ansible.builtin.command: >
    kubeadm init
    --apiserver-advertise-address=10.0.0.20
    --pod-network-cidr=10.244.0.0/16
    --node-name=k8s-master
  when: not kubeadm_init.stat.exists
  changed_when: true

- name: Création du répertoire .kube pour zeatop
  ansible.builtin.file:
    path: /home/zeatop/.kube
    state: directory
    owner: zeatop
    group: zeatop
    mode: '0755'

- name: Copie du kubeconfig pour zeatop
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/zeatop/.kube/config
    remote_src: true
    owner: zeatop
    group: zeatop
    mode: '0600'

- name: Copie du kubeconfig pour root
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copie du kubeconfig pour root
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: '0600'

- name: Installation du réseau CNI (Calico)
  ansible.builtin.command: >
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
  when: not kubeadm_init.stat.exists
  changed_when: true

- name: Génération du token de jonction
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Sauvegarde de la commande de jonction
  ansible.builtin.set_fact:
    k8s_join_command: "{{ join_command.stdout }}"

- name: Copie de la commande de jonction sur l'hôte Ansible
  ansible.builtin.copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/k8s_join_command
    mode: '0644'
  delegate_to: localhost
  become: false